/*
  Fallback content used until Sanity is connected.
  Once NEXT_PUBLIC_SANITY_PROJECT_ID is set, real CMS data replaces this.
*/

export const sampleKittens = [
  {
    _id: 'k1',
    slug: 'yukon',
    name: 'Юкон',
    litter: 'Северное сияние',
    color: 'Чёрный мрамор · n 22',
    sex: 'Кот',
    born: '2026-04-18',
    status: 'available',
    coat: { from: '#4c5147', to: '#191c17' },
    description:
      'Крупный, уверенный в себе кот с роскошными кисточками на ушах и выразительным мрамором. Отлично социализирован, ладит с детьми и другими животными.',
    images: [],
  },
  {
    _id: 'k2',
    slug: 'vishnya',
    name: 'Вишня',
    litter: 'Северное сияние',
    color: 'Рыжий мрамор · d 22',
    sex: 'Кошка',
    born: '2026-04-18',
    status: 'reserved',
    coat: { from: '#a3612f', to: '#5a2f16' },
    description:
      'Яркая рыжая кошечка с мягким характером. Любит внимание и с удовольствием сидит на руках.',
    images: [],
  },
  {
    _id: 'k3',
    slug: 'soyka',
    name: 'Сойка',
    litter: 'Хвойный',
    color: 'Голубой дым · a 22',
    sex: 'Кошка',
    born: '2026-05-02',
    status: 'available',
    coat: { from: '#7f8792', to: '#3c424a' },
    description: 'Дымчатая красавица с серебристым подшёрстком и спокойным нравом.',
    images: [],
  },
  {
    _id: 'k4',
    slug: 'kedr',
    name: 'Кедр',
    litter: 'Хвойный',
    color: 'Серебристый табби · ns 22',
    sex: 'Кот',
    born: '2026-05-02',
    status: 'available',
    coat: { from: '#9aa0a4', to: '#4a4f52' },
    description: 'Статный серебристый кот с крупным костяком — будущий чемпион.',
    images: [],
  },
  {
    _id: 'k5',
    slug: 'mgla',
    name: 'Мгла',
    litter: 'Туман',
    color: 'Чёрный дым · ns',
    sex: 'Кошка',
    born: '2026-03-11',
    status: 'sold',
    coat: { from: '#3f4038', to: '#141410' },
    description: 'Уехала в любящую семью. Загадочная чёрная дымка с изумрудными глазами.',
    images: [],
  },
  {
    _id: 'k6',
    slug: 'ryabina',
    name: 'Рябина',
    litter: 'Туман',
    color: 'Черепаховый · f',
    sex: 'Кошка',
    born: '2026-03-11',
    status: 'sold',
    coat: { from: '#6d5745', to: '#2e2419' },
    description: 'Уехала в любящую семью. Нежный черепаховый окрас и ласковый характер.',
    images: [],
  },
]

export const sampleStuds = [
  {
    _id: 's1',
    slug: 'atlas',
    name: 'Atlas of Summer Cherry',
    call: 'Атлас',
    role: 'Производитель',
    color: 'Чёрный тигровый · n 23',
    weight: '9,4 кг',
    tests: ['HCM — N/N', 'PKD — отр.', 'SMA / PK-def — чисто'],
    titles: 'Grand Champion WCF',
    coat: { from: '#565c4d', to: '#20241b' },
    images: [],
  },
  {
    _id: 's2',
    slug: 'boreas',
    name: 'Boreas Silver Wind',
    call: 'Борей',
    role: 'Производитель',
    color: 'Серебристый мрамор · ns 22',
    weight: '8,7 кг',
    tests: ['HCM — N/N', 'PKD — отр.', 'SMA / PK-def — чисто'],
    titles: 'Champion WCF',
    coat: { from: '#9aa0a4', to: '#3f4348' },
    images: [],
  },
  {
    _id: 's3',
    slug: 'taiga',
    name: 'Amber Taiga Queen',
    call: 'Тайга',
    role: 'Производительница',
    color: 'Рыжий тигровый · d 23',
    weight: '6,2 кг',
    tests: ['HCM — N/N', 'PKD — отр.', 'SMA / PK-def — чисто'],
    titles: 'Champion WCF',
    coat: { from: '#a3612f', to: '#5a2f16' },
    images: [],
  },
  {
    _id: 's4',
    slug: 'nochka',
    name: 'Noctua Black Fir',
    call: 'Ночка',
    role: 'Производительница',
    color: 'Чёрный дым · ns',
    weight: '5,9 кг',
    tests: ['HCM — N/N', 'PKD — отр.', 'SMA / PK-def — чисто'],
    titles: 'Int. Champion WCF',
    coat: { from: '#3f4038', to: '#141410' },
    images: [],
  },
]
